### ISSUE TITLE
Run failed when execute Assistant Function Calling:"object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by ctt666** [AlibabaCloudDocs/aliyun_acp_learning#2]
when I execute the code in 'p2_构造大模型问答系统/2_6_用插件扩展答疑机器人的能力边界.ipynb' for part 2.4, it turns out run failed.
Then I print the status error info, but don't konw how to handle it, the code is shown below:

```
# 引入依赖
from dashscope import Assistants, Messages, Runs, Threads
import json

# 定义公司小蜜
ChatAssistant = Assistants.create(
    # 在此指定模型名称
    model="qwen-plus",
    # 在此指定Agent名称
    name='公司小蜜',
    # 在此指定Agent的描述信息
    description='一个智能助手，能够查询员工信息，帮助员工发送请假申请，或者查询公司规章制度。',
    # 用于提示大模型所具有的工具函数能力，也可以规范输出格式
    instructions='''你是公司小蜜，你的功能有以下三个：
    1. 查询员工信息。例如：查询员工张三的HR是谁；
    2. 发送请假申请。例如：当员工提出要请假时，你可以在系统里帮他完成请假申请的发送；
    3. 查询公司规章制度。例如：我们公司项目管理的工具是什么？
    请准确判断需要调用哪个工具，并礼貌回答用户的提问。
    ''',
    # 将工具函数传入
    tools=[
        {
            # 定义工具函数类型，一般设置为function即可
            'type': 'function',
            'function': {
                # 定义工具函数名称，通过map方法映射到query_employee_info函数
                'name': '查询员工信息',
                # 定义工具函数的描述信息，Agent主要根据description来判断是否需要调用该工具函数
                'description': '当需要查询员工信息时非常有用，比如查询员工张三的HR是谁，查询教育部门总人数等。',
                # 定义工具函数的参数
                'parameters': {
                    'type': 'object',
                    'properties': {
                        # 将用户的提问作为输入参数
                        'query': {
                            'type': 'str',
                            # 对输入参数的描述
                            'description': '用户的提问。'
                        },
                    },
                    # 在此声明该工具函数需要哪些函数
                    'required': ['query']},
            }
        }
    ]
)
print(f'{ChatAssistant.name}创建完成')
# 建立Agent Function name与工具函数的映射关系
function_mapper = {
    "查询员工信息": query_employee_info
}
print('工具函数与function.name映射关系建立完成')
```

```
# 输入message信息，输出为指定Agent的回复
def get_agent_response(assistant, message=''):
    # 创建一个新的会话线程
    thread = Threads.create()
    
    # 创建一条消息并发送到该会话线程
    message = Messages.create(thread.id, content=message)
    
    # 创建一个运行实例（运行请求），将会话线程与Assistant（智能体）关联起来
    run = Runs.create(thread.id, assistant_id=assistant.id)
    
    # 等待运行完成，检查任务是否完成
    run_status = Runs.wait(run.id, thread_id=thread.id)
    
    # 如果任务运行失败，则输出错误信息
    if run_status.status == 'failed':
        print('run failed:', run_status)
        
    # 如果需要工具来辅助模型进行操作（如查询数据库、发送请求等）
    if run_status.required_action:
        # 获取需要调用的工具函数的详细信息
        f = run_status.required_action.submit_tool_outputs.tool_calls[0].function
        
        # 获取工具函数的名称（function name）
        func_name = f['name']
        
        # 获取调用工具函数时需要的输入参数
        param = json.loads(f['arguments'])
        
        # 打印出工具的名称和参数信息
        print("function is", f)
        
        # 根据工具函数的名称，通过一个映射（function_mapper）找到对应的实际工具函数
        # 这里使用了一个字典映射（function_mapper），它将工具函数名称与具体的函数对应
        if func_name in function_mapper:
            # 使用映射找到实际工具函数并传递参数，获取结果
            output = function_mapper[func_name](**param)
        else:
            # 如果找不到对应的函数，输出为空
            output = ""
        
        # 将工具函数的输出（结果）准备提交
        tool_outputs = [{
            'output': output
        }]
        
        # 提交工具的输出结果回给运行实例
        run = Runs.submit_tool_outputs(run.id, thread_id=thread.id, tool_outputs=tool_outputs)
        
        # 等待运行完成
        run_status = Runs.wait(run.id, thread_id=thread.id)
    
    # 获取最终的运行结果
    run_status = Runs.get(run.id, thread_id=thread.id)
    
    # 获取消息记录列表
    msgs = Messages.list(thread.id)
    
    # 返回Agent的回复内容
    return msgs['data'][0]['content'][0]['text']['value']

```

```
query_stk = [
    "谁是张三的HR？",
    "教育部门一共有多少员工？",
    "王五在哪个部门？",
]
for query in query_stk:
    print("提问是：")
    print(query)
    print("思考过程与最终输出是：")
    print(get_agent_response(ChatAssistant,query))
    print("\n")
```

The error info is like this:
`提问是：
谁是张三的HR？
思考过程与最终输出是：
run failed: {'tools': [{'function': {'name': '查询员工信息', 'description': '当需要查询员工信息时非常有用，比如查询员工张三的HR是谁，查询教育部门总人数等。', 'parameters': {'type': 'object', 'properties': {'query': {'type': 'str', 'description': '用户的提问。'}}, 'required': ['query']}}, 'type': 'function'}], 'required_action': None, 'id': 'run_7e2ab3ea-ef59-4482-babd-dc476af6202f', 'object': 'thread.run', 'created_at': 1734312399984, 'thread_id': 'thread_ffe44eba-8037-454f-b364-ad329d3b9ebb', 'assistant_id': 'asst_c8a5367a-e5fa-42a3-9918-f31e606fd8c9', 'status': 'failed', **'last_error': {'code': '', 'message': "object of type 'NoneType' has no len()"},** 'expires_at': None, 'started_at': None, 'cancelled_at': None, 'failed_at': 1734312400682, 'completed_at': None, 'model': 'qwen-plus', 'instructions': '你是公司小蜜，你的功能有以下三个：\n    1. 查询员工信息。例如：查询员工张三的HR是谁；\n    2. 发送请假申请。例如：当员工提出要请假时，你可以在系统里帮他完成请假申请的发送；\n    3. 查询公司规章制度。例如：我们公司项目管理的工具是什么？\n    请准确判断需要调用哪个工具，并礼貌回答用户的提问。\n    ', 'file_ids': [], 'metadata': {}, 'usage': None, 'temperature': None, 'top_p': None, 'top_k': None, 'max_tokens': None, 'truncation_strategy': None, 'tool_choice': 'auto', 'stop': '', 'enable_search': None, 'request_id': '13063b7a-0bc1-9160-8a2a-9f496ff44eaf', 'status_code': 200}
谁是张三的HR？`

**Comment by haoznic** [comment]
抱歉哈，没有及时看到。这个问题似乎已经解决了。我自己测试重新生成一次是正常的。

提问是：
谁是张三的HR？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "谁是张三的HR"}', 'output': None}
SQL语句为：SELECT HR FROM employees WHERE name = '张三'
张三的HR是李四。如果您还有其他需要帮助的地方，请随时告诉我。


提问是：
教育部门一共有多少员工？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "教育部门总人数"}', 'output': None}
SQL语句为：SELECT COUNT(*) FROM employees WHERE department = '教育部门'
教育部门共有66名员工。如果您需要更详细的信息，欢迎继续向我提问。


提问是：
王五在哪个部门？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "王五在哪个部门？"}', 'output': None}
SQL语句为：SELECT department FROM employees WHERE name = '王五'
王五在后勤部工作。

**Comment by ctt666** [comment]
嗯嗯后面发现修复了～

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/07/2025 18:50 |
| To | AlibabaCloudDocs/aliyun_acp_learning ***@***.***> |
| Cc | ctt666 ***@***.***>,
State ***@***.***> |
| Subject | Re: [AlibabaCloudDocs/aliyun_acp_learning] Run failed when execute Assistant Function Calling:"object of type 'NoneType' has no len()" (Issue #2) |

抱歉哈，没有及时看到。这个问题似乎已经解决了。我自己测试重新生成一次是正常的。

提问是：
谁是张三的HR？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "谁是张三的HR"}', 'output': None}
SQL语句为：SELECT HR FROM employees WHERE name = '张三'
张三的HR是李四。如果您还有其他需要帮助的地方，请随时告诉我。

提问是：
教育部门一共有多少员工？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "教育部门总人数"}', 'output': None}
SQL语句为：SELECT COUNT(*) FROM employees WHERE department = '教育部门'
教育部门共有66名员工。如果您需要更详细的信息，欢迎继续向我提问。

提问是：
王五在哪个部门？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "王五在哪个部门？"}', 'output': None}
SQL语句为：SELECT department FROM employees WHERE name = '王五'
王五在后勤部工作。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

haoznic left a comment (AlibabaCloudDocs/aliyun_acp_learning#2)

抱歉哈，没有及时看到。这个问题似乎已经解决了。我自己测试重新生成一次是正常的。

提问是：
谁是张三的HR？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "谁是张三的HR"}', 'output': None}
SQL语句为：SELECT HR FROM employees WHERE name = '张三'
张三的HR是李四。如果您还有其他需要帮助的地方，请随时告诉我。

提问是：
教育部门一共有多少员工？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "教育部门总人数"}', 'output': None}
SQL语句为：SELECT COUNT(*) FROM employees WHERE department = '教育部门'
教育部门共有66名员工。如果您需要更详细的信息，欢迎继续向我提问。

提问是：
王五在哪个部门？
思考过程与最终输出是：
function is {'name': '查询员工信息', 'arguments': '{"query": "王五在哪个部门？"}', 'output': None}
SQL语句为：SELECT department FROM employees WHERE name = '王五'
王五在后勤部工作。
